# Generated by Django 3.0 on 2021-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='color',
        ),
        migrations.RemoveField(
            model_name='set',
            name='name',
        ),
        migrations.RemoveField(
            model_name='set',
            name='ripe',
        ),
        migrations.AddField(
            model_name='set',
            name='rep_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='set_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
